
INSTALLDIR=/usr/local/bin

default: hexdump

hexdump:hexdump.c
	cc -o hexdump hexdump.c

clean:
	-rm hexdump

#install:
#	install -m755 hexdump $(INSTALLDIR)/	
#
#uninstall:
#	-rm $(INSTALLDIR)/hexdump
